# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'urscape_importer_form.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_urscape_importer_form(object):
    def setupUi(self, urscape_importer_form):
        urscape_importer_form.setObjectName("urscape_importer_form")
        urscape_importer_form.resize(500, 720)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(urscape_importer_form.sizePolicy().hasHeightForWidth())
        urscape_importer_form.setSizePolicy(sizePolicy)
        urscape_importer_form.setMinimumSize(QtCore.QSize(400, 0))
        self.gridLayout_3 = QtWidgets.QGridLayout(urscape_importer_form)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.progressBar = QtWidgets.QProgressBar(urscape_importer_form)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setInvertedAppearance(False)
        self.progressBar.setObjectName("progressBar")
        self.horizontalLayout_6.addWidget(self.progressBar)
        self.btnCancel = QtWidgets.QPushButton(urscape_importer_form)
        self.btnCancel.setEnabled(False)
        self.btnCancel.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.btnCancel.setObjectName("btnCancel")
        self.horizontalLayout_6.addWidget(self.btnCancel)
        self.gridLayout_3.addLayout(self.horizontalLayout_6, 4, 0, 1, 2)
        self.lblCredit = QtWidgets.QLabel(urscape_importer_form)
        self.lblCredit.setTextFormat(QtCore.Qt.AutoText)
        self.lblCredit.setAlignment(QtCore.Qt.AlignCenter)
        self.lblCredit.setWordWrap(True)
        self.lblCredit.setObjectName("lblCredit")
        self.gridLayout_3.addWidget(self.lblCredit, 7, 0, 1, 2)
        spacerItem = QtWidgets.QSpacerItem(20, 5, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_3.addItem(spacerItem, 2, 0, 1, 2)
        self.tabWidget = QtWidgets.QTabWidget(urscape_importer_form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.tabWidget.setObjectName("tabWidget")
        self.tabParams = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabParams.sizePolicy().hasHeightForWidth())
        self.tabParams.setSizePolicy(sizePolicy)
        self.tabParams.setObjectName("tabParams")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.tabParams)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.scrollArea = QtWidgets.QScrollArea(self.tabParams)
        self.scrollArea.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.scrollArea.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.scrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.scrollArea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.scrollArea.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 555, 1225))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_9.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridLayout_9.setContentsMargins(10, 10, 10, 10)
        self.gridLayout_9.setSpacing(10)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.wgtDate = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.wgtDate.setObjectName("wgtDate")
        self.hblDate = QtWidgets.QHBoxLayout(self.wgtDate)
        self.hblDate.setContentsMargins(0, 0, 0, 0)
        self.hblDate.setObjectName("hblDate")
        self.lblYYYY = QtWidgets.QLabel(self.wgtDate)
        self.lblYYYY.setObjectName("lblYYYY")
        self.hblDate.addWidget(self.lblYYYY)
        self.txtYYYY = QtWidgets.QLineEdit(self.wgtDate)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtYYYY.sizePolicy().hasHeightForWidth())
        self.txtYYYY.setSizePolicy(sizePolicy)
        self.txtYYYY.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.txtYYYY.setText("")
        self.txtYYYY.setObjectName("txtYYYY")
        self.hblDate.addWidget(self.txtYYYY)
        self.lblMM = QtWidgets.QLabel(self.wgtDate)
        self.lblMM.setObjectName("lblMM")
        self.hblDate.addWidget(self.lblMM)
        self.txtMM = QtWidgets.QLineEdit(self.wgtDate)
        self.txtMM.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.txtMM.setObjectName("txtMM")
        self.hblDate.addWidget(self.txtMM)
        self.lblDD = QtWidgets.QLabel(self.wgtDate)
        self.lblDD.setObjectName("lblDD")
        self.hblDate.addWidget(self.lblDD)
        self.txtDD = QtWidgets.QLineEdit(self.wgtDate)
        self.txtDD.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.txtDD.setObjectName("txtDD")
        self.hblDate.addWidget(self.txtDD)
        self.gridLayout_9.addWidget(self.wgtDate, 16, 5, 1, 1)
        self.wgtCitation = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.wgtCitation.setObjectName("wgtCitation")
        self.hblCitation = QtWidgets.QHBoxLayout(self.wgtCitation)
        self.hblCitation.setContentsMargins(0, 0, 0, 0)
        self.hblCitation.setObjectName("hblCitation")
        self.txtCitation = QtWidgets.QLineEdit(self.wgtCitation)
        self.txtCitation.setObjectName("txtCitation")
        self.hblCitation.addWidget(self.txtCitation)
        self.chkMandatory = QtWidgets.QCheckBox(self.wgtCitation)
        self.chkMandatory.setEnabled(True)
        self.chkMandatory.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.chkMandatory.setChecked(False)
        self.chkMandatory.setObjectName("chkMandatory")
        self.hblCitation.addWidget(self.chkMandatory)
        self.gridLayout_9.addWidget(self.wgtCitation, 25, 5, 1, 1)
        self.wgtMaxPatchSize = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.wgtMaxPatchSize.setObjectName("wgtMaxPatchSize")
        self.hblMaxPatchSize = QtWidgets.QHBoxLayout(self.wgtMaxPatchSize)
        self.hblMaxPatchSize.setContentsMargins(0, 0, 0, 0)
        self.hblMaxPatchSize.setObjectName("hblMaxPatchSize")
        self.txtMaxPatchSize = QtWidgets.QLineEdit(self.wgtMaxPatchSize)
        self.txtMaxPatchSize.setEnabled(False)
        self.txtMaxPatchSize.setObjectName("txtMaxPatchSize")
        self.hblMaxPatchSize.addWidget(self.txtMaxPatchSize)
        self.lblResPatchUnit = QtWidgets.QLabel(self.wgtMaxPatchSize)
        self.lblResPatchUnit.setObjectName("lblResPatchUnit")
        self.hblMaxPatchSize.addWidget(self.lblResPatchUnit)
        self.chkMaxPatchSizeOverride = QtWidgets.QCheckBox(self.wgtMaxPatchSize)
        self.chkMaxPatchSizeOverride.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.chkMaxPatchSizeOverride.setObjectName("chkMaxPatchSizeOverride")
        self.hblMaxPatchSize.addWidget(self.chkMaxPatchSizeOverride)
        self.gridLayout_9.addWidget(self.wgtMaxPatchSize, 33, 5, 1, 1)
        self.wgtCustomUnits = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.wgtCustomUnits.setObjectName("wgtCustomUnits")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.wgtCustomUnits)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lblCustomUnits = QtWidgets.QLabel(self.wgtCustomUnits)
        self.lblCustomUnits.setObjectName("lblCustomUnits")
        self.horizontalLayout.addWidget(self.lblCustomUnits)
        self.txtCustomUnits = QtWidgets.QLineEdit(self.wgtCustomUnits)
        self.txtCustomUnits.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.txtCustomUnits.setObjectName("txtCustomUnits")
        self.horizontalLayout.addWidget(self.txtCustomUnits)
        self.chkRelative = QtWidgets.QCheckBox(self.wgtCustomUnits)
        self.chkRelative.setEnabled(True)
        self.chkRelative.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.chkRelative.setChecked(False)
        self.chkRelative.setObjectName("chkRelative")
        self.horizontalLayout.addWidget(self.chkRelative)
        self.gridLayout_9.addWidget(self.wgtCustomUnits, 15, 5, 1, 1)
        self.frmHLineOptionalParams = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frmHLineOptionalParams.sizePolicy().hasHeightForWidth())
        self.frmHLineOptionalParams.setSizePolicy(sizePolicy)
        self.frmHLineOptionalParams.setMinimumSize(QtCore.QSize(10, 0))
        self.frmHLineOptionalParams.setSizeIncrement(QtCore.QSize(10, 0))
        self.frmHLineOptionalParams.setBaseSize(QtCore.QSize(10, 0))
        self.frmHLineOptionalParams.setFrameShape(QtWidgets.QFrame.HLine)
        self.frmHLineOptionalParams.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frmHLineOptionalParams.setObjectName("frmHLineOptionalParams")
        self.formLayout_2 = QtWidgets.QFormLayout(self.frmHLineOptionalParams)
        self.formLayout_2.setContentsMargins(0, 0, 0, 0)
        self.formLayout_2.setObjectName("formLayout_2")
        self.gridLayout_9.addWidget(self.frmHLineOptionalParams, 17, 0, 1, 6)
        self.wgtLayerColorGrp = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.wgtLayerColorGrp.setObjectName("wgtLayerColorGrp")
        self.hblLayerColor = QtWidgets.QHBoxLayout(self.wgtLayerColorGrp)
        self.hblLayerColor.setContentsMargins(0, 0, 0, 0)
        self.hblLayerColor.setSpacing(10)
        self.hblLayerColor.setObjectName("hblLayerColor")
        self.cmbLayerColor = QtWidgets.QComboBox(self.wgtLayerColorGrp)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbLayerColor.sizePolicy().hasHeightForWidth())
        self.cmbLayerColor.setSizePolicy(sizePolicy)
        self.cmbLayerColor.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.cmbLayerColor.setObjectName("cmbLayerColor")
        self.hblLayerColor.addWidget(self.cmbLayerColor)
        self.wgtLayerColor = QtWidgets.QWidget(self.wgtLayerColorGrp)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.wgtLayerColor.sizePolicy().hasHeightForWidth())
        self.wgtLayerColor.setSizePolicy(sizePolicy)
        self.wgtLayerColor.setMinimumSize(QtCore.QSize(75, 0))
        self.wgtLayerColor.setObjectName("wgtLayerColor")
        self.hblLayerColor.addWidget(self.wgtLayerColor)
        self.gridLayout_9.addWidget(self.wgtLayerColorGrp, 19, 5, 1, 1)
        self.wgtCustomRes = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.wgtCustomRes.setObjectName("wgtCustomRes")
        self.gridLayout = QtWidgets.QGridLayout(self.wgtCustomRes)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.lblCustomRes = QtWidgets.QLabel(self.wgtCustomRes)
        self.lblCustomRes.setObjectName("lblCustomRes")
        self.gridLayout.addWidget(self.lblCustomRes, 0, 0, 1, 1)
        self.txtCustomRes = QtWidgets.QLineEdit(self.wgtCustomRes)
        self.txtCustomRes.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.txtCustomRes.setObjectName("txtCustomRes")
        self.gridLayout.addWidget(self.txtCustomRes, 0, 1, 1, 1)
        self.lblCustomResNote = QtWidgets.QLabel(self.wgtCustomRes)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setItalic(True)
        self.lblCustomResNote.setFont(font)
        self.lblCustomResNote.setObjectName("lblCustomResNote")
        self.gridLayout.addWidget(self.lblCustomResNote, 1, 0, 1, 3)
        self.lblMeters = QtWidgets.QLabel(self.wgtCustomRes)
        self.lblMeters.setObjectName("lblMeters")
        self.gridLayout.addWidget(self.lblMeters, 0, 2, 1, 1)
        self.gridLayout_9.addWidget(self.wgtCustomRes, 13, 5, 1, 1)
        self.wgtChkboxes = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.wgtChkboxes.sizePolicy().hasHeightForWidth())
        self.wgtChkboxes.setSizePolicy(sizePolicy)
        self.wgtChkboxes.setObjectName("wgtChkboxes")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.wgtChkboxes)
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.chkClipToNoDataOuterArea = QtWidgets.QCheckBox(self.wgtChkboxes)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chkClipToNoDataOuterArea.sizePolicy().hasHeightForWidth())
        self.chkClipToNoDataOuterArea.setSizePolicy(sizePolicy)
        self.chkClipToNoDataOuterArea.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.chkClipToNoDataOuterArea.setObjectName("chkClipToNoDataOuterArea")
        self.verticalLayout.addWidget(self.chkClipToNoDataOuterArea)
        self.chkKeepSameResAsInput = QtWidgets.QCheckBox(self.wgtChkboxes)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chkKeepSameResAsInput.sizePolicy().hasHeightForWidth())
        self.chkKeepSameResAsInput.setSizePolicy(sizePolicy)
        self.chkKeepSameResAsInput.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.chkKeepSameResAsInput.setObjectName("chkKeepSameResAsInput")
        self.verticalLayout.addWidget(self.chkKeepSameResAsInput)
        self.chkPreventHigherRes = QtWidgets.QCheckBox(self.wgtChkboxes)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chkPreventHigherRes.sizePolicy().hasHeightForWidth())
        self.chkPreventHigherRes.setSizePolicy(sizePolicy)
        self.chkPreventHigherRes.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.chkPreventHigherRes.setChecked(True)
        self.chkPreventHigherRes.setObjectName("chkPreventHigherRes")
        self.verticalLayout.addWidget(self.chkPreventHigherRes)
        self.chkFixGeometry = QtWidgets.QCheckBox(self.wgtChkboxes)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chkFixGeometry.sizePolicy().hasHeightForWidth())
        self.chkFixGeometry.setSizePolicy(sizePolicy)
        self.chkFixGeometry.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.chkFixGeometry.setObjectName("chkFixGeometry")
        self.verticalLayout.addWidget(self.chkFixGeometry)
        self.chkClipToQGISCanvas = QtWidgets.QCheckBox(self.wgtChkboxes)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chkClipToQGISCanvas.sizePolicy().hasHeightForWidth())
        self.chkClipToQGISCanvas.setSizePolicy(sizePolicy)
        self.chkClipToQGISCanvas.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.chkClipToQGISCanvas.setObjectName("chkClipToQGISCanvas")
        self.verticalLayout.addWidget(self.chkClipToQGISCanvas)
        self.gridLayout_9.addWidget(self.wgtChkboxes, 38, 5, 1, 1)
        self.wgtNoDataValue = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.wgtNoDataValue.sizePolicy().hasHeightForWidth())
        self.wgtNoDataValue.setSizePolicy(sizePolicy)
        self.wgtNoDataValue.setObjectName("wgtNoDataValue")
        self.hblNoDataValue = QtWidgets.QHBoxLayout(self.wgtNoDataValue)
        self.hblNoDataValue.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.hblNoDataValue.setContentsMargins(0, 0, 0, 0)
        self.hblNoDataValue.setObjectName("hblNoDataValue")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.txtNoData = QtWidgets.QLineEdit(self.wgtNoDataValue)
        self.txtNoData.setObjectName("txtNoData")
        self.verticalLayout_5.addWidget(self.txtNoData)
        self.wgtListNoDatas = QtWidgets.QWidget(self.wgtNoDataValue)
        self.wgtListNoDatas.setObjectName("wgtListNoDatas")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.wgtListNoDatas)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.wgtVblNoDatas = QtWidgets.QWidget(self.wgtListNoDatas)
        self.wgtVblNoDatas.setObjectName("wgtVblNoDatas")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.wgtVblNoDatas)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.vblNoDatas = QtWidgets.QVBoxLayout()
        self.vblNoDatas.setContentsMargins(-1, -1, 0, -1)
        self.vblNoDatas.setObjectName("vblNoDatas")
        self.verticalLayout_6.addLayout(self.vblNoDatas)
        self.gridLayout_2.addWidget(self.wgtVblNoDatas, 0, 0, 1, 1)
        self.verticalLayout_5.addWidget(self.wgtListNoDatas)
        spacerItem1 = QtWidgets.QSpacerItem(20, 1, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem1)
        self.hblNoDataValue.addLayout(self.verticalLayout_5)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.chkNoDataList = QtWidgets.QCheckBox(self.wgtNoDataValue)
        self.chkNoDataList.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.chkNoDataList.setObjectName("chkNoDataList")
        self.verticalLayout_4.addWidget(self.chkNoDataList)
        spacerItem2 = QtWidgets.QSpacerItem(20, 1, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem2)
        self.hblNoDataValue.addLayout(self.verticalLayout_4)
        self.gridLayout_9.addWidget(self.wgtNoDataValue, 36, 5, 1, 1)
        self.wgtCustomLayerColor = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.wgtCustomLayerColor.setObjectName("wgtCustomLayerColor")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.wgtCustomLayerColor)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(7)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.vblHue = QtWidgets.QVBoxLayout()
        self.vblHue.setObjectName("vblHue")
        self.lblHue = QtWidgets.QLabel(self.wgtCustomLayerColor)
        self.lblHue.setObjectName("lblHue")
        self.vblHue.addWidget(self.lblHue)
        spacerItem3 = QtWidgets.QSpacerItem(28, 28, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.vblHue.addItem(spacerItem3)
        self.horizontalLayout_4.addLayout(self.vblHue)
        self.vblHueSlider = QtWidgets.QVBoxLayout()
        self.vblHueSlider.setContentsMargins(0, 0, -1, 0)
        self.vblHueSlider.setObjectName("vblHueSlider")
        self.hsCustomColor = QtWidgets.QSlider(self.wgtCustomLayerColor)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.hsCustomColor.sizePolicy().hasHeightForWidth())
        self.hsCustomColor.setSizePolicy(sizePolicy)
        self.hsCustomColor.setMinimumSize(QtCore.QSize(0, 30))
        self.hsCustomColor.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.hsCustomColor.setMaximum(360)
        self.hsCustomColor.setSingleStep(1)
        self.hsCustomColor.setPageStep(10)
        self.hsCustomColor.setOrientation(QtCore.Qt.Horizontal)
        self.hsCustomColor.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.hsCustomColor.setTickInterval(30)
        self.hsCustomColor.setObjectName("hsCustomColor")
        self.vblHueSlider.addWidget(self.hsCustomColor)
        self.hblHueMinMax = QtWidgets.QHBoxLayout()
        self.hblHueMinMax.setObjectName("hblHueMinMax")
        self.lblHueMin = QtWidgets.QLabel(self.wgtCustomLayerColor)
        self.lblHueMin.setObjectName("lblHueMin")
        self.hblHueMinMax.addWidget(self.lblHueMin)
        spacerItem4 = QtWidgets.QSpacerItem(58, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.hblHueMinMax.addItem(spacerItem4)
        self.lblHueMax = QtWidgets.QLabel(self.wgtCustomLayerColor)
        self.lblHueMax.setObjectName("lblHueMax")
        self.hblHueMinMax.addWidget(self.lblHueMax)
        self.vblHueSlider.addLayout(self.hblHueMinMax)
        self.horizontalLayout_4.addLayout(self.vblHueSlider)
        self.gridLayout_9.addWidget(self.wgtCustomLayerColor, 20, 5, 1, 1)
        self.frmHLineAdvancedParams = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frmHLineAdvancedParams.sizePolicy().hasHeightForWidth())
        self.frmHLineAdvancedParams.setSizePolicy(sizePolicy)
        self.frmHLineAdvancedParams.setMinimumSize(QtCore.QSize(10, 0))
        self.frmHLineAdvancedParams.setSizeIncrement(QtCore.QSize(10, 0))
        self.frmHLineAdvancedParams.setBaseSize(QtCore.QSize(10, 0))
        self.frmHLineAdvancedParams.setFrameShape(QtWidgets.QFrame.HLine)
        self.frmHLineAdvancedParams.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frmHLineAdvancedParams.setObjectName("frmHLineAdvancedParams")
        self.formLayout_5 = QtWidgets.QFormLayout(self.frmHLineAdvancedParams)
        self.formLayout_5.setContentsMargins(0, 0, 0, 0)
        self.formLayout_5.setObjectName("formLayout_5")
        self.gridLayout_9.addWidget(self.frmHLineAdvancedParams, 27, 0, 1, 6)
        self.frmHLineMandatoryParams = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frmHLineMandatoryParams.sizePolicy().hasHeightForWidth())
        self.frmHLineMandatoryParams.setSizePolicy(sizePolicy)
        self.frmHLineMandatoryParams.setMinimumSize(QtCore.QSize(10, 0))
        self.frmHLineMandatoryParams.setSizeIncrement(QtCore.QSize(10, 0))
        self.frmHLineMandatoryParams.setBaseSize(QtCore.QSize(10, 0))
        self.frmHLineMandatoryParams.setFrameShape(QtWidgets.QFrame.HLine)
        self.frmHLineMandatoryParams.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frmHLineMandatoryParams.setObjectName("frmHLineMandatoryParams")
        self.formLayout_3 = QtWidgets.QFormLayout(self.frmHLineMandatoryParams)
        self.formLayout_3.setContentsMargins(0, 0, 0, 0)
        self.formLayout_3.setObjectName("formLayout_3")
        self.gridLayout_9.addWidget(self.frmHLineMandatoryParams, 6, 0, 1, 6)
        self.wgtShapefileField = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.wgtShapefileField.setObjectName("wgtShapefileField")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.wgtShapefileField)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.cmbShapefileField = QtWidgets.QComboBox(self.wgtShapefileField)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbShapefileField.sizePolicy().hasHeightForWidth())
        self.cmbShapefileField.setSizePolicy(sizePolicy)
        self.cmbShapefileField.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.cmbShapefileField.setObjectName("cmbShapefileField")
        self.horizontalLayout_7.addWidget(self.cmbShapefileField)
        self.btnOpenAttributeTable = QtWidgets.QPushButton(self.wgtShapefileField)
        self.btnOpenAttributeTable.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.btnOpenAttributeTable.setObjectName("btnOpenAttributeTable")
        self.horizontalLayout_7.addWidget(self.btnOpenAttributeTable)
        self.gridLayout_9.addWidget(self.wgtShapefileField, 3, 5, 1, 1)
        self.frmHLineMetadata = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frmHLineMetadata.sizePolicy().hasHeightForWidth())
        self.frmHLineMetadata.setSizePolicy(sizePolicy)
        self.frmHLineMetadata.setMinimumSize(QtCore.QSize(10, 0))
        self.frmHLineMetadata.setSizeIncrement(QtCore.QSize(10, 0))
        self.frmHLineMetadata.setBaseSize(QtCore.QSize(10, 0))
        self.frmHLineMetadata.setFrameShape(QtWidgets.QFrame.HLine)
        self.frmHLineMetadata.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frmHLineMetadata.setObjectName("frmHLineMetadata")
        self.formLayout_4 = QtWidgets.QFormLayout(self.frmHLineMetadata)
        self.formLayout_4.setContentsMargins(0, 0, 0, 0)
        self.formLayout_4.setObjectName("formLayout_4")
        self.gridLayout_9.addWidget(self.frmHLineMetadata, 22, 0, 1, 6)
        self.lblRoadClasses = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.lblRoadClasses.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblRoadClasses.setObjectName("lblRoadClasses")
        self.gridLayout_9.addWidget(self.lblRoadClasses, 29, 3, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(17, 5, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_9.addItem(spacerItem5, 39, 0, 1, 6)
        self.lblNoDataValue = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblNoDataValue.sizePolicy().hasHeightForWidth())
        self.lblNoDataValue.setSizePolicy(sizePolicy)
        self.lblNoDataValue.setMinimumSize(QtCore.QSize(0, 0))
        self.lblNoDataValue.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.lblNoDataValue.setIndent(4)
        self.lblNoDataValue.setObjectName("lblNoDataValue")
        self.gridLayout_9.addWidget(self.lblNoDataValue, 36, 3, 1, 1)
        self.cmbNoDataCalculation = QtWidgets.QComboBox(self.scrollAreaWidgetContents)
        self.cmbNoDataCalculation.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.cmbNoDataCalculation.setObjectName("cmbNoDataCalculation")
        self.gridLayout_9.addWidget(self.cmbNoDataCalculation, 35, 5, 1, 1)
        self.lblRasterBand = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.lblRasterBand.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblRasterBand.setObjectName("lblRasterBand")
        self.gridLayout_9.addWidget(self.lblRasterBand, 32, 1, 1, 3)
        self.txtRasterBand = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.txtRasterBand.setObjectName("txtRasterBand")
        self.gridLayout_9.addWidget(self.txtRasterBand, 32, 5, 1, 1)
        self.lblMaxPatchSize = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.lblMaxPatchSize.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblMaxPatchSize.setObjectName("lblMaxPatchSize")
        self.gridLayout_9.addWidget(self.lblMaxPatchSize, 33, 1, 1, 3)
        self.lblResamplingMthd = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.lblResamplingMthd.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblResamplingMthd.setObjectName("lblResamplingMthd")
        self.gridLayout_9.addWidget(self.lblResamplingMthd, 34, 0, 1, 4)
        self.cmbResamplingMthd = QtWidgets.QComboBox(self.scrollAreaWidgetContents)
        self.cmbResamplingMthd.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.cmbResamplingMthd.setObjectName("cmbResamplingMthd")
        self.gridLayout_9.addWidget(self.cmbResamplingMthd, 34, 5, 1, 1)
        self.lblNoDataCalculation = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.lblNoDataCalculation.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblNoDataCalculation.setObjectName("lblNoDataCalculation")
        self.gridLayout_9.addWidget(self.lblNoDataCalculation, 35, 0, 1, 4)
        self.lblAdvParams = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lblAdvParams.setFont(font)
        self.lblAdvParams.setObjectName("lblAdvParams")
        self.gridLayout_9.addWidget(self.lblAdvParams, 28, 0, 1, 6)
        self.txtURLLink = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.txtURLLink.setObjectName("txtURLLink")
        self.gridLayout_9.addWidget(self.txtURLLink, 26, 5, 1, 1)
        self.lblURLLink = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.lblURLLink.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblURLLink.setObjectName("lblURLLink")
        self.gridLayout_9.addWidget(self.lblURLLink, 26, 3, 1, 1)
        self.lblCitation = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.lblCitation.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblCitation.setObjectName("lblCitation")
        self.gridLayout_9.addWidget(self.lblCitation, 25, 3, 1, 1)
        self.txtSource = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.txtSource.setObjectName("txtSource")
        self.gridLayout_9.addWidget(self.txtSource, 24, 5, 1, 1)
        self.lblSource = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.lblSource.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblSource.setObjectName("lblSource")
        self.gridLayout_9.addWidget(self.lblSource, 24, 3, 1, 1)
        self.lblMetadata = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lblMetadata.setFont(font)
        self.lblMetadata.setObjectName("lblMetadata")
        self.gridLayout_9.addWidget(self.lblMetadata, 23, 0, 1, 6)
        self.txtLayerGroup = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.txtLayerGroup.setInputMask("")
        self.txtLayerGroup.setText("")
        self.txtLayerGroup.setObjectName("txtLayerGroup")
        self.gridLayout_9.addWidget(self.txtLayerGroup, 21, 5, 1, 1)
        self.lblLayerGroup = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.lblLayerGroup.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblLayerGroup.setObjectName("lblLayerGroup")
        self.gridLayout_9.addWidget(self.lblLayerGroup, 21, 1, 1, 3)
        self.lblLayerColor = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.lblLayerColor.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblLayerColor.setObjectName("lblLayerColor")
        self.gridLayout_9.addWidget(self.lblLayerColor, 19, 2, 1, 2)
        self.lblOptionalParams = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lblOptionalParams.setFont(font)
        self.lblOptionalParams.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lblOptionalParams.setObjectName("lblOptionalParams")
        self.gridLayout_9.addWidget(self.lblOptionalParams, 18, 0, 1, 6)
        self.lblDate = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.lblDate.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblDate.setObjectName("lblDate")
        self.gridLayout_9.addWidget(self.lblDate, 16, 3, 1, 1)
        self.cmbUnits = QtWidgets.QComboBox(self.scrollAreaWidgetContents)
        self.cmbUnits.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.cmbUnits.setEditable(False)
        self.cmbUnits.setCurrentText("")
        self.cmbUnits.setObjectName("cmbUnits")
        self.gridLayout_9.addWidget(self.cmbUnits, 14, 5, 1, 1)
        self.lblUnits = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.lblUnits.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblUnits.setObjectName("lblUnits")
        self.gridLayout_9.addWidget(self.lblUnits, 14, 3, 1, 1)
        self.cmbRes = QtWidgets.QComboBox(self.scrollAreaWidgetContents)
        self.cmbRes.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.cmbRes.setObjectName("cmbRes")
        self.gridLayout_9.addWidget(self.cmbRes, 12, 5, 1, 1)
        self.lblRes = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.lblRes.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblRes.setObjectName("lblRes")
        self.gridLayout_9.addWidget(self.lblRes, 12, 3, 1, 1)
        self.txtLocation = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.txtLocation.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.txtLocation.setObjectName("txtLocation")
        self.gridLayout_9.addWidget(self.txtLocation, 11, 5, 1, 1)
        self.lblLocation = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.lblLocation.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblLocation.setObjectName("lblLocation")
        self.gridLayout_9.addWidget(self.lblLocation, 11, 3, 1, 1)
        self.txtLayerName = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.txtLayerName.setEnabled(True)
        self.txtLayerName.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.txtLayerName.setText("")
        self.txtLayerName.setObjectName("txtLayerName")
        self.gridLayout_9.addWidget(self.txtLayerName, 10, 5, 1, 1)
        self.lblLayerName = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.lblLayerName.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblLayerName.setObjectName("lblLayerName")
        self.gridLayout_9.addWidget(self.lblLayerName, 10, 2, 1, 2)
        self.hblOutputPath = QtWidgets.QHBoxLayout()
        self.hblOutputPath.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.hblOutputPath.setSpacing(7)
        self.hblOutputPath.setObjectName("hblOutputPath")
        self.txtOutputPath = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.txtOutputPath.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.txtOutputPath.setText("")
        self.txtOutputPath.setObjectName("txtOutputPath")
        self.hblOutputPath.addWidget(self.txtOutputPath)
        self.btnBrowse = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.btnBrowse.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.btnBrowse.setObjectName("btnBrowse")
        self.hblOutputPath.addWidget(self.btnBrowse)
        self.gridLayout_9.addLayout(self.hblOutputPath, 9, 5, 1, 1)
        self.lblOutputPath = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.lblOutputPath.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblOutputPath.setObjectName("lblOutputPath")
        self.gridLayout_9.addWidget(self.lblOutputPath, 9, 1, 1, 3)
        self.cmbOutputType = QtWidgets.QComboBox(self.scrollAreaWidgetContents)
        self.cmbOutputType.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.cmbOutputType.setObjectName("cmbOutputType")
        self.gridLayout_9.addWidget(self.cmbOutputType, 8, 5, 1, 1)
        self.lblOutputType = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.lblOutputType.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblOutputType.setObjectName("lblOutputType")
        self.gridLayout_9.addWidget(self.lblOutputType, 8, 1, 1, 3)
        self.lblMandatoryParams = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lblMandatoryParams.setFont(font)
        self.lblMandatoryParams.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lblMandatoryParams.setObjectName("lblMandatoryParams")
        self.gridLayout_9.addWidget(self.lblMandatoryParams, 7, 0, 1, 6)
        self.lblShapefileField = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.lblShapefileField.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblShapefileField.setObjectName("lblShapefileField")
        self.gridLayout_9.addWidget(self.lblShapefileField, 3, 1, 1, 3)
        self.lblQGISInput = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lblQGISInput.setFont(font)
        self.lblQGISInput.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lblQGISInput.setObjectName("lblQGISInput")
        self.gridLayout_9.addWidget(self.lblQGISInput, 1, 0, 1, 6)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.cmbInputLayer = QtWidgets.QComboBox(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbInputLayer.sizePolicy().hasHeightForWidth())
        self.cmbInputLayer.setSizePolicy(sizePolicy)
        self.cmbInputLayer.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.cmbInputLayer.setObjectName("cmbInputLayer")
        self.horizontalLayout_2.addWidget(self.cmbInputLayer)
        self.btnRefresh = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.btnRefresh.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.btnRefresh.setObjectName("btnRefresh")
        self.horizontalLayout_2.addWidget(self.btnRefresh)
        self.gridLayout_9.addLayout(self.horizontalLayout_2, 2, 5, 1, 1)
        self.lblQLayer = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.lblQLayer.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblQLayer.setObjectName("lblQLayer")
        self.gridLayout_9.addWidget(self.lblQLayer, 2, 2, 1, 2)
        self.cmbRoadClasses = QtWidgets.QComboBox(self.scrollAreaWidgetContents)
        self.cmbRoadClasses.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.cmbRoadClasses.setObjectName("cmbRoadClasses")
        self.gridLayout_9.addWidget(self.cmbRoadClasses, 29, 5, 1, 1)
        self.wgtNetworkMap = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.wgtNetworkMap.sizePolicy().hasHeightForWidth())
        self.wgtNetworkMap.setSizePolicy(sizePolicy)
        self.wgtNetworkMap.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.wgtNetworkMap.setObjectName("wgtNetworkMap")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.wgtNetworkMap)
        self.gridLayout_8.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.glNetworkMap = QtWidgets.QGridLayout()
        self.glNetworkMap.setObjectName("glNetworkMap")
        self.gridLayout_8.addLayout(self.glNetworkMap, 0, 0, 1, 1)
        self.gridLayout_9.addWidget(self.wgtNetworkMap, 30, 3, 1, 3)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout_4.addWidget(self.scrollArea, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tabParams, "")
        self.tabLog = QtWidgets.QWidget()
        self.tabLog.setObjectName("tabLog")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.tabLog)
        self.gridLayout_5.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.scrollArea_2 = QtWidgets.QScrollArea(self.tabLog)
        self.scrollArea_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 98, 85))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollAreaWidgetContents_2.sizePolicy().hasHeightForWidth())
        self.scrollAreaWidgetContents_2.setSizePolicy(sizePolicy)
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents_2)
        self.gridLayout_6.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridLayout_6.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_6.setSpacing(7)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.txtLog = QtWidgets.QPlainTextEdit(self.scrollAreaWidgetContents_2)
        self.txtLog.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.txtLog.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.txtLog.setReadOnly(True)
        self.txtLog.setObjectName("txtLog")
        self.gridLayout_6.addWidget(self.txtLog, 0, 0, 1, 1)
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_2)
        self.gridLayout_5.addWidget(self.scrollArea_2, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tabLog, "")
        self.gridLayout_3.addWidget(self.tabWidget, 1, 0, 1, 2)
        spacerItem6 = QtWidgets.QSpacerItem(20, 5, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.gridLayout_3.addItem(spacerItem6, 6, 0, 1, 2)
        self.hblRunClose = QtWidgets.QHBoxLayout()
        self.hblRunClose.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.hblRunClose.setContentsMargins(0, 0, 0, -1)
        self.hblRunClose.setSpacing(10)
        self.hblRunClose.setObjectName("hblRunClose")
        self.btnPrevSettings = QtWidgets.QPushButton(urscape_importer_form)
        self.btnPrevSettings.setObjectName("btnPrevSettings")
        self.hblRunClose.addWidget(self.btnPrevSettings)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.hblRunClose.addItem(spacerItem7)
        self.btnRun = QtWidgets.QPushButton(urscape_importer_form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnRun.sizePolicy().hasHeightForWidth())
        self.btnRun.setSizePolicy(sizePolicy)
        self.btnRun.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.btnRun.setObjectName("btnRun")
        self.hblRunClose.addWidget(self.btnRun)
        self.btnClose = QtWidgets.QPushButton(urscape_importer_form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnClose.sizePolicy().hasHeightForWidth())
        self.btnClose.setSizePolicy(sizePolicy)
        self.btnClose.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.btnClose.setObjectName("btnClose")
        self.hblRunClose.addWidget(self.btnClose)
        self.gridLayout_3.addLayout(self.hblRunClose, 5, 0, 1, 2)

        self.retranslateUi(urscape_importer_form)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(urscape_importer_form)
        urscape_importer_form.setTabOrder(self.cmbInputLayer, self.btnRefresh)
        urscape_importer_form.setTabOrder(self.btnRefresh, self.cmbShapefileField)
        urscape_importer_form.setTabOrder(self.cmbShapefileField, self.btnOpenAttributeTable)
        urscape_importer_form.setTabOrder(self.btnOpenAttributeTable, self.cmbOutputType)
        urscape_importer_form.setTabOrder(self.cmbOutputType, self.txtOutputPath)
        urscape_importer_form.setTabOrder(self.txtOutputPath, self.btnBrowse)
        urscape_importer_form.setTabOrder(self.btnBrowse, self.txtLayerName)
        urscape_importer_form.setTabOrder(self.txtLayerName, self.txtLocation)
        urscape_importer_form.setTabOrder(self.txtLocation, self.cmbRes)
        urscape_importer_form.setTabOrder(self.cmbRes, self.txtCustomRes)
        urscape_importer_form.setTabOrder(self.txtCustomRes, self.cmbUnits)
        urscape_importer_form.setTabOrder(self.cmbUnits, self.txtCustomUnits)
        urscape_importer_form.setTabOrder(self.txtCustomUnits, self.chkRelative)
        urscape_importer_form.setTabOrder(self.chkRelative, self.txtYYYY)
        urscape_importer_form.setTabOrder(self.txtYYYY, self.txtMM)
        urscape_importer_form.setTabOrder(self.txtMM, self.txtDD)
        urscape_importer_form.setTabOrder(self.txtDD, self.cmbLayerColor)
        urscape_importer_form.setTabOrder(self.cmbLayerColor, self.hsCustomColor)
        urscape_importer_form.setTabOrder(self.hsCustomColor, self.txtLayerGroup)
        urscape_importer_form.setTabOrder(self.txtLayerGroup, self.txtSource)
        urscape_importer_form.setTabOrder(self.txtSource, self.txtCitation)
        urscape_importer_form.setTabOrder(self.txtCitation, self.chkMandatory)
        urscape_importer_form.setTabOrder(self.chkMandatory, self.txtURLLink)
        urscape_importer_form.setTabOrder(self.txtURLLink, self.wgtNetworkMap)
        urscape_importer_form.setTabOrder(self.wgtNetworkMap, self.txtRasterBand)
        urscape_importer_form.setTabOrder(self.txtRasterBand, self.txtMaxPatchSize)
        urscape_importer_form.setTabOrder(self.txtMaxPatchSize, self.chkMaxPatchSizeOverride)
        urscape_importer_form.setTabOrder(self.chkMaxPatchSizeOverride, self.cmbResamplingMthd)
        urscape_importer_form.setTabOrder(self.cmbResamplingMthd, self.cmbNoDataCalculation)
        urscape_importer_form.setTabOrder(self.cmbNoDataCalculation, self.txtNoData)
        urscape_importer_form.setTabOrder(self.txtNoData, self.chkNoDataList)
        urscape_importer_form.setTabOrder(self.chkNoDataList, self.chkClipToNoDataOuterArea)
        urscape_importer_form.setTabOrder(self.chkClipToNoDataOuterArea, self.chkKeepSameResAsInput)
        urscape_importer_form.setTabOrder(self.chkKeepSameResAsInput, self.chkPreventHigherRes)
        urscape_importer_form.setTabOrder(self.chkPreventHigherRes, self.chkFixGeometry)
        urscape_importer_form.setTabOrder(self.chkFixGeometry, self.chkClipToQGISCanvas)
        urscape_importer_form.setTabOrder(self.chkClipToQGISCanvas, self.btnCancel)
        urscape_importer_form.setTabOrder(self.btnCancel, self.btnPrevSettings)
        urscape_importer_form.setTabOrder(self.btnPrevSettings, self.btnRun)
        urscape_importer_form.setTabOrder(self.btnRun, self.btnClose)
        urscape_importer_form.setTabOrder(self.btnClose, self.scrollArea)
        urscape_importer_form.setTabOrder(self.scrollArea, self.tabWidget)
        urscape_importer_form.setTabOrder(self.tabWidget, self.txtLog)
        urscape_importer_form.setTabOrder(self.txtLog, self.scrollArea_2)

    def retranslateUi(self, urscape_importer_form):
        _translate = QtCore.QCoreApplication.translate
        urscape_importer_form.setWindowTitle(_translate("urscape_importer_form", "ur-scape Data Importer"))
        self.btnCancel.setText(_translate("urscape_importer_form", "Cancel"))
        self.lblCredit.setText(_translate("urscape_importer_form", "This plugin was developed by the Future Cities Laboratory"))
        self.lblYYYY.setText(_translate("urscape_importer_form", "Year"))
        self.txtYYYY.setPlaceholderText(_translate("urscape_importer_form", "YYYY"))
        self.lblMM.setText(_translate("urscape_importer_form", "Month"))
        self.txtMM.setPlaceholderText(_translate("urscape_importer_form", "MM"))
        self.lblDD.setText(_translate("urscape_importer_form", "Day"))
        self.txtDD.setPlaceholderText(_translate("urscape_importer_form", "DD"))
        self.txtCitation.setPlaceholderText(_translate("urscape_importer_form", "e.g. Website Name. Publisher, Publication date..."))
        self.chkMandatory.setText(_translate("urscape_importer_form", "Mandatory"))
        self.txtMaxPatchSize.setText(_translate("urscape_importer_form", "1"))
        self.lblResPatchUnit.setText(_translate("urscape_importer_form", "degrees"))
        self.chkMaxPatchSizeOverride.setText(_translate("urscape_importer_form", "Override"))
        self.lblCustomUnits.setText(_translate("urscape_importer_form", "Value"))
        self.chkRelative.setText(_translate("urscape_importer_form", "Relative"))
        self.lblCustomRes.setText(_translate("urscape_importer_form", "Value"))
        self.lblCustomResNote.setText(_translate("urscape_importer_form", "* Values < 1 or > 1000 meters are not recommended"))
        self.lblMeters.setText(_translate("urscape_importer_form", "meters"))
        self.chkClipToNoDataOuterArea.setText(_translate("urscape_importer_form", "Clip To No Data Outer Area"))
        self.chkKeepSameResAsInput.setText(_translate("urscape_importer_form", "Keep Same Resolution as Input"))
        self.chkPreventHigherRes.setText(_translate("urscape_importer_form", "Prevent Higher Resolution"))
        self.chkFixGeometry.setText(_translate("urscape_importer_form", "Fix Geometry (Very Slow)"))
        self.chkClipToQGISCanvas.setText(_translate("urscape_importer_form", "Clip to QGIS Canvas"))
        self.txtNoData.setText(_translate("urscape_importer_form", "n/a"))
        self.chkNoDataList.setText(_translate("urscape_importer_form", "List"))
        self.lblHue.setText(_translate("urscape_importer_form", "Hue"))
        self.lblHueMin.setText(_translate("urscape_importer_form", "0"))
        self.lblHueMax.setText(_translate("urscape_importer_form", "360"))
        self.btnOpenAttributeTable.setText(_translate("urscape_importer_form", "Open Attribute Table"))
        self.lblRoadClasses.setText(_translate("urscape_importer_form", "Road Classes"))
        self.lblNoDataValue.setText(_translate("urscape_importer_form", "No Data Value"))
        self.lblRasterBand.setText(_translate("urscape_importer_form", "Raster Band"))
        self.txtRasterBand.setToolTip(_translate("urscape_importer_form", "Set the band for multi-band data (default is 1)"))
        self.txtRasterBand.setText(_translate("urscape_importer_form", "1"))
        self.lblMaxPatchSize.setText(_translate("urscape_importer_form", "Max Patch Size"))
        self.lblResamplingMthd.setText(_translate("urscape_importer_form", "Resampling Method"))
        self.lblNoDataCalculation.setText(_translate("urscape_importer_form", "No Data Calculation"))
        self.lblAdvParams.setText(_translate("urscape_importer_form", "Advanced Parameters"))
        self.txtURLLink.setPlaceholderText(_translate("urscape_importer_form", "e.g. www.nasa.com"))
        self.lblURLLink.setText(_translate("urscape_importer_form", "URL Link"))
        self.lblCitation.setText(_translate("urscape_importer_form", "Citation"))
        self.txtSource.setPlaceholderText(_translate("urscape_importer_form", "e.g. Nasa"))
        self.lblSource.setText(_translate("urscape_importer_form", "Source"))
        self.lblMetadata.setText(_translate("urscape_importer_form", "Metadata"))
        self.txtLayerGroup.setPlaceholderText(_translate("urscape_importer_form", "e.g. Demography"))
        self.lblLayerGroup.setText(_translate("urscape_importer_form", "Layer Group"))
        self.lblLayerColor.setText(_translate("urscape_importer_form", "Layer Color"))
        self.lblOptionalParams.setText(_translate("urscape_importer_form", "Optional Parameters"))
        self.lblDate.setText(_translate("urscape_importer_form", "Date"))
        self.lblUnits.setText(_translate("urscape_importer_form", "Units"))
        self.cmbRes.setToolTip(_translate("urscape_importer_form", "Items change depending on whether Location is \"World\" or otherwise"))
        self.lblRes.setText(_translate("urscape_importer_form", "Resolution"))
        self.txtLocation.setToolTip(_translate("urscape_importer_form", "e.g. World"))
        self.txtLocation.setPlaceholderText(_translate("urscape_importer_form", "e.g. Singapore"))
        self.lblLocation.setText(_translate("urscape_importer_form", "Location"))
        self.txtLayerName.setToolTip(_translate("urscape_importer_form", "e.g. Population Density"))
        self.txtLayerName.setPlaceholderText(_translate("urscape_importer_form", "e.g. Population Density"))
        self.lblLayerName.setText(_translate("urscape_importer_form", "Layer Name"))
        self.txtOutputPath.setToolTip(_translate("urscape_importer_form", "Use \'/\' for path separator"))
        self.txtOutputPath.setPlaceholderText(_translate("urscape_importer_form", "Users/username/Desktop"))
        self.btnBrowse.setText(_translate("urscape_importer_form", "Browse"))
        self.lblOutputPath.setText(_translate("urscape_importer_form", "Output Path"))
        self.lblOutputType.setText(_translate("urscape_importer_form", "Output Type"))
        self.lblMandatoryParams.setText(_translate("urscape_importer_form", "Mandatory Parameters"))
        self.lblShapefileField.setText(_translate("urscape_importer_form", "Field"))
        self.lblQGISInput.setText(_translate("urscape_importer_form", "QGIS Input"))
        self.btnRefresh.setText(_translate("urscape_importer_form", "Refresh"))
        self.lblQLayer.setText(_translate("urscape_importer_form", " Input Layer"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabParams), _translate("urscape_importer_form", "Parameters"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabLog), _translate("urscape_importer_form", "Log"))
        self.btnPrevSettings.setText(_translate("urscape_importer_form", "Previous Settings"))
        self.btnRun.setText(_translate("urscape_importer_form", "Run"))
        self.btnClose.setText(_translate("urscape_importer_form", "Close"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    urscape_importer_form = QtWidgets.QDialog()
    ui = Ui_urscape_importer_form()
    ui.setupUi(urscape_importer_form)
    urscape_importer_form.show()
    sys.exit(app.exec_())

